### ISSUE TITLE
Where to put org files?

### ISSUE THREAD

**Issue by jethrokuan** [rasendubi/braindump#2]
Was just trying this one repo out earlier, where do you put the Org files? Putting them in /public didn't seem to work, like it did with the barebones repo.

**Comment by jethrokuan** [comment]
Ah I found it, in "posts". Looks good, will add mathjax support, and then might replace mine.

**Comment by jethrokuan** [comment]
Ah would've been nice to use, but not doesn't support id links, which is sort of a deal breaker for me now.

**Comment by rasendubi** [comment]
Sorry, missed this issue. GitHub did not notify me :(

For MathJax, I have added katex recently. For id links, they should be easy to add—I'll try to do that today.

What other features do you need from braindump? (I want to make [org-braindump example](https://github.com/rasendubi/uniorg/tree/master/examples/org-braindump) a generic braindump export tool and keep this one to adjust for my idiosyncrasies.)

**Comment by rasendubi** [comment]
Well, it's not exactly “easy,” but here is a [limited support for id: links](https://github.com/rasendubi/braindump/commit/41e2428f769b8d4200915f375592b88e483e8e7a). File-level ids work as expected, headline-level ids point to the target file and not specific headline. At least no broken links are generated…

To properly support headline-level ids, I need to properly generate headline anchors (preferably stable), support CUSTOM_ID, etc.
